// Generated by https://quicktype.io
export interface DataUser {
  name:          string;
  lastNameP:       string;
  lastNameM:       string;
  email:          string;
  pregunta:       string;
  respuesta:      string;
}
